name: banksy
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python=3.11
  - jupyter
  - h5py
  - scanpy
  - leidenalg
  - harmony-pytorch
  - R
  - rpy2
  - pip
  - pip:
    - pybanksy

# conda env create -y -f conda_banksy.yml
# conda env update -f conda_banksy.yml