---
title: "CellChat analysis"
author: "Ethan Hung"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
# general
options(max.print = 300)
options(stringsAsFactors = FALSE)
library(dplyr)
library(here)
library(ggplot2)
library(cowplot)
library(circlize)

# single-cell general
library(BiocParallel)
library(scater)
library(Seurat)
library(patchwork)

# analysis-specific
library(CellChat)
library(ComplexHeatmap)
library(NMF)
library(ggalluvial)
source(here("src", "single_cell", "cellchat.R"))

#' https://htmlpreview.github.io/?https://github.com/jinworks/CellChat/blob/master/tutorial/CellChat-vignette.html
#' https://htmlpreview.github.io/?https://github.com/jinworks/CellChat/blob/master/tutorial/Comparison_analysis_of_multiple_datasets.html
```

# Setup

```{r Prep Objects}
savename <- "cellchat_NEURON"
DATADIR <- here("data", "processed", "external")
CELLCHAT_DIR <- here(DATADIR, "tools", "cellchat")
PLOT_DIR <- here("plots", "pailin", savename)
load.seurat <- FALSE

if (load.seurat == TRUE) {
  seurat_object <- readRDS(here(DATADIR, "analyzed.rds"))
  seurat_object <- NormalizeData(seurat_object)
  Idents(seurat_object) <- seurat_object$celltype
  timepoints <- levels(seurat_object$timepoint)
  seurat_object$sample[1]
  
  seurat_s1 <- subset(seurat_object, sample == seurat_object$sample[1])
  p <- DimPlot(seurat_s1, reduction = "spatial", group.by = "celltype", dims = c(1, 2))
  
  ratio <- 4/3 #um per px
  p +
    geom_circle(aes(x0 = x0, y0 = y0, r = r), data = data.frame(x0 = 7500, y0 = 2000, r = 250/ratio), inherit.aes = FALSE, color = "black", fill = NA, linewidth = 1) +
    coord_fixed() +
    geom_circle(aes(x0 = x0, y0 = y0, r = r), data = data.frame(x0 = 7500, y0 = 2000, r = 100/ratio), inherit.aes = FALSE, color = "black", fill = NA, linewidth = 1) +
    coord_fixed()
} else {
  timepoints <- c("pbs", "7dpi", "3wpi")
}

relevant.celltypes <- c("Neu Phox2b+", "Airway neurons")
available_slots <- c("net")
max <- length(timepoints)
comparisons <- list(c("pbs","7dpi"), c("pbs","3wpi"), c("7dpi","3wpi"))
comparisons_int <- list(c(1,2), c(1,3), c(2,3))

# read in cellchat objects
cellchat.TIMEPOINTS <- lapply(
  here(CELLCHAT_DIR,paste0(savename, "_", timepoints, ".rds")),
  function(x) readRDS(x)
)
names(cellchat.TIMEPOINTS) <- timepoints

# cellchat.MERGED <- mergeCellChat(cellchat.TIMEPOINTS, add.names = names(cellchat.TIMEPOINTS))
# available_slots <- if (pathway) c("net", "netP") else c("net")
# for (slot in available_slots) {
#   cellchat.MERGED <- computeNetSimilarityPairwise(cellchat.MERGED, type = "functional", slot.name = slot)
#   cellchat.MERGED <- netEmbedding(cellchat.MERGED, type = "functional", slot.name = slot)
#   cellchat.MERGED <- netClustering(cellchat.MERGED, type = "functional", slot.name = slot)
# }

cellchat.NEURONS_MERGED <- readRDS(here(CELLCHAT_DIR, paste0(savename, "_MERGED", ".rds")))

# show celltypes
all.celltypes <- levels(cellchat.TIMEPOINTS_MERGED@idents$joint)
```

# Plotting

```{r CellChat Overview Plots}
#'------------------------------------------------------------------------------
#'---------------------------    General Overview    ---------------------------
#'------------------------------------------------------------------------------

dir.create(here(PLOT_DIR, "Overview"), showWarnings = F, recursive = T)
m <- "weight"

# Merged timepoints
groupSize <- cellchat.TIMEPOINTS_MERGED@idents[["joint"]] %>% table() %>% as.numeric()

for (n in 1:length(comparisons)) {
  title <- paste(comparisons[[n]], collapse = " vs ")
  print(title)
  
  # CIRCOPLOT Δ
  jpeg(
    here(PLOT_DIR, "Overview", paste0("Differential_Circo-", title, ".jpg")),
    width = 3000, height = 3000, res = 300, type = "cairo")
  netVisual_diffInteraction(
    cellchat.TIMEPOINTS_MERGED,
    weight.scale = T,
    vertex.weight = groupSize,
    comparison = comparisons[[n]],
    measure = m,
    title.name=paste(title, "circo"),
    margin = 0.4)
  # dev.off()

  # HEATMAP Δ
  jpeg(
    here(PLOT_DIR, "Overview", paste0("Differential_Heatmap-", title, ".jpg")),
    width = 3000, height = 3000, res = 300, type = "cairo")
  netVisual_heatmap(
    cellchat.TIMEPOINTS_MERGED,
    comparison = comparisons[[n]],
    slot.name = "net",
    measure=m,
    title.name=paste(title, "heatmap"),
    cluster.rows=T,
    cluster.cols=T) %>% draw()
  dev.off()


  # SCATTER Δ
  if ("netP" %in% available_slots) {
    f <- netAnalysis_diff_signalingRole_scatter(
      cellchat.TIMEPOINTS_MERGED,
      title = paste(title, "signaling strength"),
      comparison = comparisons_int[[n]],
      slot.name = "netP")
    ggsave(
      here(PLOT_DIR, "Overview", paste0("Differential_Scatter_Pathway-", title, ".jpg")),
      plot=f,
      width = 3000, height = 3000, dpi = 300, units="px")
  }

  # BARPLOT Δ
  for (slot in available_slots) {
    gg1 <- rankNet(
      cellchat.TIMEPOINTS_MERGED,
      mode = "comparison", comparison=comparisons_int[[n]],
      slot.name = slot,
      measure = m,
      stacked = T,
      do.stat = TRUE)
    height <- if (slot == "net") 12000 else 3000
    version <- if (slot == "net") "LR" else "Pathway"
    ggsave(
      here(PLOT_DIR, "Overview", paste0("Differential_Indiv_Barplot_", version, "-", title, ".jpg")),
      plot=gg1,
      width = 2000, height = height, dpi = 300, units="px")
  }
}

# BARPLOT SUM
f <- list()
for (m in c("count", "weight")) {
  f[[m]] <- compareInteractions(
    cellchat.TIMEPOINTS_MERGED,
    measure = m,
    show.legend = T,
    title.name = title)
}
ggsave(
  here(PLOT_DIR, "Overview", paste0("Differential_Total_Barplot.jpg")),
  plot = wrap_plots(f),
  width = 3000, height = 1000, dpi = 300, units="px")

{ # Individual timepoints
  num.link <- sapply(cellchat.TIMEPOINTS, function(x) {rowSums(x@net$count) + colSums(x@net$count)-diag(x@net$count)})
  weight.MinMax <- c(min(num.link), max(num.link)) # control the dot size in the different datasets
  
  # SCATTER
  for (slot in available_slots) {
    f <- list()
    for (tp in names(cellchat.TIMEPOINTS)) {
      f[[tp]] <- netAnalysis_signalingRole_scatter(
        cellchat.TIMEPOINTS[[tp]],
        title = paste(tp, "signaling strength"),
        weight.MinMax = weight.MinMax,
        slot.name = slot)
    }
    version <- if (slot == "net") "LR" else "Pathway"
    ggsave(
      here(PLOT_DIR, "Overview", paste0("Total_In_Out_Scatter_", version, ".jpg")),
      plot=wrap_plots(f, nrow = 1),
      width = 6000, height = 2000, dpi = 300, units="px")
  }
  
  
  { # CIRCOPLOT
    jpeg(
      here(PLOT_DIR, "Overview", paste0("Total_Circo.jpg")),
      width = 9000, height = 3000, res = 300, type = "cairo")
    par(mfrow = c(1,max), mar = c(1,1,1,1))
    for (n in 1:max) {
      groupSize <- cellchat.TIMEPOINTS[[timepoints[n]]]@idents %>% table() %>% as.numeric()
      netVisual_circle(
        cellchat.TIMEPOINTS[[timepoints[n]]]@net[[m]],
        vertex.weight = groupSize,
        weight.scale = T,
        label.edge= F,
        margin = 0.4,
        title.name = paste("Interaction", m, "by celltype,", timepoints[n]))
      if (n < max) par(fig = c(n/max, (n+1)/max, 0, 1), new = TRUE)
    }
    dev.off()
  }
  
  { # CHORDPLOT
    jpeg(
      here(PLOT_DIR, "Overview", paste0("Total_Chord.jpg")),
      width = 9000, height = 3000, res = 300, type = "cairo")
    par(mfrow = c(1,max), mar = c(1,1,1,1))
    for (n in 1:max) {
      chordDiagram(cellchat.TIMEPOINTS[[timepoints[n]]]@net[[m]], 
               grid.col = scPalette(length(levels(cellchat.TIMEPOINTS[[timepoints[n]]]@idents))),
               transparency = 0.5,
               directional = 1,
               direction.type = c("diffHeight", "arrows"),
               link.arr.type = "big.arrow")
      title(main = paste("Interaction", m, "by celltype,", timepoints[n]))
      circos.clear()
      if (n < max) par(fig = c(n/max, (n+1)/max, 0, 1), new = TRUE)
    }
    dev.off()
  }
}
```

```{r Cell Type Specific}
#'------------------------------------------------------------------------------
#'--------------------------    Cell Type Specific    --------------------------
#'------------------------------------------------------------------------------

m <- "weight"

for (celltype in relevant.celltypes) {
  dir.create(here(PLOT_DIR, celltype), showWarnings = F, recursive = T)
  
  # Merged timepoints
  groupSize <- cellchat.TIMEPOINTS_MERGED@idents[["joint"]] %>% table() %>% as.numeric()
  
  for (n in 1:length(comparisons)) {
    title <- paste(comparisons[[n]], collapse = " vs ")
    
    
    # CIRCOPLOT Δ
    jpeg(
      here(PLOT_DIR, celltype, paste0("Differential_Circo-", title, ".jpg")),
      width = 6000, height = 3000, res = 300, type = "cairo")
    par(mfrow = c(1,2), mar = c(1,1,1,1))
    
    netVisual_diffInteraction(
      cellchat.TIMEPOINTS_MERGED,
      weight.scale = T,
      vertex.weight = groupSize,
      sources.use = celltype,
      # targets.use = celltype,
      comparison = comparisons[[n]],
      measure = m,
      title.name = title,
      margin = 0.4)
    
    par(fig = c(0.5, 1, 0, 1), new = TRUE)
    
    netVisual_diffInteraction(
      cellchat.TIMEPOINTS_MERGED,
      weight.scale = T,
      vertex.weight = groupSize,
      # sources.use = celltype,
      targets.use = celltype,
      comparison = comparisons[[n]],
      measure = m,
      title.name = title,
      margin = 0.4)
    dev.off()
  
    # BARPLOT Δ
    for (slot in available_slots) {
      gg1 <- rankNet(
        cellchat.TIMEPOINTS_MERGED,
        mode = "comparison", comparison=comparisons_int[[n]],
        slot.name = slot,
        sources.use = celltype,
        targets.use = "Fibroblasts",
        measure = m,
        stacked = T,
        do.stat = TRUE,
        title = paste(celltype, "outgoing signaling"))
      
      gg2 <- rankNet(
        cellchat.TIMEPOINTS_MERGED,
        mode = "comparison", comparison=comparisons_int[[n]],
        slot.name = slot,
        targets.use = celltype,
        targets.use = "Fibroblasts",
        measure = m,
        stacked = T,
        do.stat = TRUE,
        title = paste(celltype, "incoming signaling"))
      
      height <- if (slot == "net") 24000 else 6000
      version <- if (slot == "net") "LR" else "Pathway"
      ggsave(
        here(PLOT_DIR, celltype, paste0("Differential_Indiv_Barplot_", version, "-", title, ".jpg")),
        plot=gg1 + gg2,
        width = 2000, height = height, dpi = 300, units="px", limitsize = FALSE)
    }
  }
  
  # Individual timepoints
  
  { # CIRCOPLOT
    jpeg(
      here(PLOT_DIR, celltype, paste0("Total_Circo.jpg")),
      width = 9000, height = 3000, res = 300, type = "cairo")
    par(mfrow = c(1,max), mar = c(1,1,1,1))
    for (n in 1:max) {
      groupSize <- cellchat.TIMEPOINTS[[timepoints[n]]]@idents %>% table() %>% as.numeric()
      netVisual_circle(
        cellchat.TIMEPOINTS[[timepoints[n]]]@net[[m]],
        vertex.weight = groupSize,
        idents.use = celltype,
        weight.scale = T,
        label.edge= F,
        margin = 0.4,
        title.name = paste("Interaction", m, "by celltype,", timepoints[n]))
      if (n < max) par(fig = c(n/max, (n+1)/max, 0, 1), new = TRUE)
    }
    dev.off()
  }
    
  # BUBBLE
  for (tp in timepoints) {
    gg1 <- netVisual_bubble(cellchat.TIMEPOINTS[[tp]], sources.use = celltype, title.name=paste("Outgoing", celltype, "LR pairs"))
    gg2 <- netVisual_bubble(cellchat.TIMEPOINTS[[tp]], targets.use = celltype, title.name=paste("Incoming", celltype, "LR pairs"))
    ggsave(
      here(PLOT_DIR, celltype, paste0("Total_SigLR_Bubble-", tp, ".jpg")),
      plot=gg1 + gg2,
      width = 8000, height = 9000, dpi = 300, units="px", limitsize = FALSE)
  }
}
```

```{r Extras}
for (celltype in relevant.celltypes) {
  dir.create(here(PLOT_DIR, celltype), showWarnings = F, recursive = T)
  
  # Merged timepoints
  groupSize <- cellchat.TIMEPOINTS_MERGED@idents[["joint"]] %>% table() %>% as.numeric()
  
  for (n in 1:length(comparisons)) {
    title <- paste(comparisons[[n]], collapse = " vs ")
  
    # BARPLOT Δ
    for (slot in available_slots) {
      gg1 <- rankNet(
        cellchat.TIMEPOINTS_MERGED,
        mode = "comparison", comparison=comparisons_int[[n]],
        slot.name = slot,
        sources.use = celltype,
        targets.use = "Fibroblasts",
        measure = m,
        stacked = T,
        do.stat = TRUE,
        title = paste(celltype, "outgoing signaling"))
      
      gg2 <- rankNet(
        cellchat.TIMEPOINTS_MERGED,
        mode = "comparison", comparison=comparisons_int[[n]],
        slot.name = slot,
        targets.use = celltype,
        targets.use = "Fibroblasts",
        measure = m,
        stacked = T,
        do.stat = TRUE,
        title = paste(celltype, "incoming signaling"))
      
      height <- if (slot == "net") 24000 else 6000
      version <- if (slot == "net") "LR" else "Pathway"
      ggsave(
        here(PLOT_DIR, "extras", paste0("FB-Phox2b RankNet", version, "-", title, ".jpg")),
        plot=gg1 + gg2,
        width = 2000, height = height, dpi = 300, units="px", limitsize = FALSE)
    }
  }
}

cellchat.MERGED <- mergeCellChat(cellchat.TIMEPOINTS, add.names = names(cellchat.TIMEPOINTS))

gg1 <- netVisual_bubble(
  cellchat.MERGED,
  sources.use = celltype,
  targets.use = "Fibroblasts",
  comparison = c(1, 2),
  # max.dataset = 2,
  # title.name = "Increased signaling in LS",
  angle.x = 45,
  remove.isolate = T)

gg2 <- netVisual_bubble(
  cellchat.TIMEPOINTS[["pbs"]],
  sources.use = c(celltype),
  targets.use = c("Fibroblasts"),
  # comparison = c(1, 2),
  # angle.x = 45
)



dir.create(here(PLOT_DIR, "Neurons Grouped"), showWarnings = F, recursive = T)
folder.name <- "Neurons Grouped"
celltype <- "Neurons"
m <- "weight.merged"

cell.idents <- as.character(cellchat.TIMEPOINTS[[1]]@idents)
groupSize <- replace(cell.idents,grepl("neu", cell.idents, ignore.case = TRUE), "Neurons") %>%
  table() %>% as.numeric()
print(groupSize)

{ # CIRCOPLOT
  jpeg(
    here(PLOT_DIR, folder.name, paste0("Total_Circo.jpg")),
    width = 6000, height = 2000, res = 300, type = "cairo")
  par(mfrow = c(1,max), mar = c(1,1,1,1))
  for (n in 1:max) {
    netVisual_circle(
      cellchat.TIMEPOINTS[[timepoints[n]]]@net[[m]],
      vertex.weight = groupSize,
      weight.scale = T,
      label.edge= F,
      margin = 0.4,
      title.name = paste("Interaction", m, "by celltype,", timepoints[n]))
    if (n < max) par(fig = c(n/max, (n+1)/max, 0, 1), new = TRUE)
  }
  dev.off()
}

for (n in 1:length(comparisons)) {
  title <- paste(comparisons[[n]], collapse = " vs ")
  # CIRCOPLOT Δ
  jpeg(
    here(PLOT_DIR, folder.name, paste0("Differential_Circo-", title, ".jpg")),
    width = 3000, height = 3000, res = 300, type = "cairo")
  netVisual_diffInteraction(
    cellchat.TIMEPOINTS_MERGED,
    weight.scale = T,
    vertex.weight = groupSize,
    comparison = comparisons[[n]],
    measure = m,
    title.name=paste(title, "circo"),
    margin = 0.4)
  dev.off()
}

{ # CIRCOPLOT
  jpeg(
    here(PLOT_DIR, folder.name, paste0("Total_Circo-Neuron Grouped ONLY.jpg")),
    width = 9000, height = 3000, res = 300, type = "cairo")
  par(mfrow = c(1,max), mar = c(1,1,1,1))
  for (n in 1:max) {
    cell.idents <- as.character(cellchat.TIMEPOINTS[[timepoints[n]]]@idents)
    groupSize <- replace(cell.idents,grepl("neu", cell.idents, ignore.case = TRUE), "Neurons") %>%
      table() %>% as.numeric()
    print(groupSize)
    netVisual_circle(
      cellchat.TIMEPOINTS[[timepoints[n]]]@net[[m]],
      vertex.weight = groupSize,
      idents.use = celltype,
      weight.scale = T,
      label.edge= F,
      margin = 0.4,
      title.name = paste("Interaction", m, "by celltype,", timepoints[n]))
    if (n < max) par(fig = c(n/max, (n+1)/max, 0, 1), new = TRUE)
  }
  dev.off()
}

```

# Archive

```{r cellchat plots UNUSED}
# Celltype scatterplots differential in/outgoing LR pairs
# celltypes.of.interest <- c("OPC", "Astrocytes", "Airway neurons", "Oligodendrocytes", "Excitatory neurons", "Inhibitory neurons", "Neu Phox2b+", "Neu ")
celltypes.of.interest <- c("Neu Phox2b+")

# only use if comparing net (not needed for netP)
slot <- "netP"
if (slot == "net"){
  all_LR <- unique(unlist(lapply(cellchat.TIMEPOINTS_MERGED@LR, function(x) x$LRsig$interaction_name)))
} else {
  all_LR <- NULL
}

for (celltype in celltypes.of.interest) {
  for (tp in c(2,3)) {
    netAnalysis_signalingChanges_scatter(
      cellchat.TIMEPOINTS_MERGED,
      idents.use = celltype,
      comparison = c(tp, 1),
      slot.name = slot,
      signaling = all_LR,
      top.label = 0.1
    )
  }
}

# joint embedding of loadings
for (slot in c("net", "netP")){
  netVisual_embeddingPairwise(
    cellchat.TIMEPOINTS_MERGED,
    type = "functional",
    slot.name = slot,
    label.size = 3.5)
  
  rankSimilarity(
    cellchat.TIMEPOINTS_MERGED,
    comparison2=c(1,2,3),
    type = "functional",
    slot.name = slot)
}


```

```{r NeuronChat}
neuronchat <- readRDS(here(CELLCHAT_DIR,"neuronchat_ALL.rds"))

groupSize <- neuronchat@idents %>% table() %>% as.numeric()
net <- NeuronChat::net_aggregation(neuronchat@net, method = "weight")
netVisual_circle_neuron(
  net,
  vertex.weight=groupSize,
  vertex.size.max=20,
  arrow.size = 0.5,margin=0.3,edge.width.max=8)

cell_prox <- NeuronChat::cell_proximity_enrichment_score_multiple(
    meta = neuronchat@meta,
    celltype_label = "celltype",
    centroid_x = "spatial1",
    centroid_y = "spatial2",
    slice_id    = "sample",
    thresh_dist = 400 # microns
)

# 9. Visualization outputs

netVisual_spatial(seurat_obj, spatial_links) # layered spatial plot
```

# Custom Database

<https://htmlpreview.github.io/?https://github.com/jinworks/CellChat/blob/master/tutorial/Update-CellChatDB.html>

```{r}
load(url("https://github.com/Wei-BioMath/NeuronChat/raw/main/data/interactionDB_human.rda"))
neuron_df <- as.data.frame(do.call(rbind, lapply(interactionDB_human, function(x) {
    data.frame(
        interaction_name = x$interaction_name,
        ligand = x$lig_contributor,
        receptor = x$receptor_subunit,
        lig_contributor = x$lig_contributor,
        receptor_subunit = x$receptor_subunit,
        interaction_type = x$interaction_type,
        ligant_type = x$ligand_type,
        stringsAsFactors = FALSE
    )
})))
neuronChatDB <- create_custom_cellchat_db(neuron_df, evidence = "NeuronChat")
ethanDB <- create_custom_cellchat_db(read.csv(here("references", "ethan_ccc_database.csv")))
```
